Repository exercism/lfe, pull requests merged in 2024-05, with the labels that each got.

#225 Update space-age test suite
  exercises/practice/space-age/.meta/tests.toml
Labels: x:rep/tiny

#231 Update phone-number files
  config.json
  exercises/practice/phone-number/.meta/config.json
  exercises/practice/phone-number/.meta/example.lfe
  exercises/practice/phone-number/src/phone-number.app.src
  exercises/practice/phone-number/src/phone-number.lfe
  exercises/practice/phone-number/src/phone.lfe
  exercises/practice/phone-number/test/phone-number-tests.lfe
  exercises/practice/phone-number/test/phone-tests.lfe
Labels: x:module/practice-exercise, x:rep/large

#232 Fix broken app.src and rebar files for resistor-color-duo
  exercises/practice/resistor-color-duo/rebar.config
  exercises/practice/resistor-color-duo/rebar.lock
  exercises/practice/resistor-color-duo/src/resistor-color-duo.app.src
Labels: x:rep/tiny

#233 Sync tests for allergies
  exercises/practice/allergies/.meta/tests.toml
  exercises/practice/allergies/src/allergies.lfe
  exercises/practice/allergies/test/allergies-tests.lfe
Labels: x:action/sync, x:rep/small

#234 Sync anagram tests
  exercises/practice/anagram/.meta/tests.toml
  exercises/practice/anagram/src/anagram.lfe
  exercises/practice/anagram/test/anagram-tests.lfe
Labels: x:action/sync, x:rep/tiny

#235 Add missing tests for atbash-cipher
  exercises/practice/atbash-cipher/src/atbash-cipher.lfe
  exercises/practice/atbash-cipher/test/atbash-cipher-tests.lfe
Labels: x:action/sync, x:rep/tiny

#237 Add missing exercise authors
  exercises/practice/atbash-cipher/.meta/config.json
  exercises/practice/binary/.meta/config.json
  exercises/practice/circular-buffer/.meta/config.json
  exercises/practice/difference-of-squares/.meta/config.json
  exercises/practice/largest-series-product/.meta/config.json
  exercises/practice/meetup/.meta/config.json
  exercises/practice/parallel-letter-frequency/.meta/config.json
  exercises/practice/robot-simulator/.meta/config.json
  exercises/practice/series/.meta/config.json
Labels: x:rep/tiny

#240 anagram: sync
  exercises/practice/anagram/.docs/instructions.md
  exercises/practice/anagram/.docs/introduction.md
Labels: x:size/tiny

#239 Add isogram
  config.json
  exercises/practice/isogram/.docs/instructions.md
  exercises/practice/isogram/.gitignore
  exercises/practice/isogram/.meta/config.json
  exercises/practice/isogram/.meta/example.lfe
  exercises/practice/isogram/.meta/tests.toml
  exercises/practice/isogram/Makefile
  exercises/practice/isogram/rebar.config
  exercises/practice/isogram/rebar.lock
  exercises/practice/isogram/src/isogram.app.src
  exercises/practice/isogram/src/isogram.lfe
  exercises/practice/isogram/test/isogram-tests.lfe
Labels: x:module/practice-exercise, x:rep/large

#241 Rename nucleotide-count files and sync tests
  exercises/practice/nucleotide-count/.meta/config.json
  exercises/practice/nucleotide-count/.meta/example.lfe
  exercises/practice/nucleotide-count/src/dna.lfe
  exercises/practice/nucleotide-count/src/nucleotide-count.app.src
  exercises/practice/nucleotide-count/src/nucleotide-count.lfe
  exercises/practice/nucleotide-count/test/dna-tests.lfe
  exercises/practice/nucleotide-count/test/nucleotide-count-tests.lfe
Labels: x:rep/small

#245 Add secret-handshake
  config.json
  exercises/practice/secret-handshake/.docs/instructions.md
  exercises/practice/secret-handshake/.docs/introduction.md
  exercises/practice/secret-handshake/.gitignore
  exercises/practice/secret-handshake/.meta/config.json
  exercises/practice/secret-handshake/.meta/example.lfe
  exercises/practice/secret-handshake/.meta/tests.toml
  exercises/practice/secret-handshake/Makefile
  exercises/practice/secret-handshake/rebar.config
  exercises/practice/secret-handshake/rebar.lock
  exercises/practice/secret-handshake/src/secret-handshake.app.src
  exercises/practice/secret-handshake/src/secret-handshake.lfe
  exercises/practice/secret-handshake/test/secret-handshake-tests.lfe
Labels: x:module/practice-exercise, x:rep/large

#246 bank-account: sync
  exercises/practice/bank-account/.docs/instructions.md
  exercises/practice/bank-account/.docs/introduction.md
Labels: x:size/tiny

#247 Add armstrong-numbers
  config.json
  exercises/practice/armstrong-numbers/.docs/instructions.md
  exercises/practice/armstrong-numbers/.gitignore
  exercises/practice/armstrong-numbers/.meta/config.json
  exercises/practice/armstrong-numbers/.meta/example.lfe
  exercises/practice/armstrong-numbers/.meta/tests.toml
  exercises/practice/armstrong-numbers/Makefile
  exercises/practice/armstrong-numbers/rebar.config
  exercises/practice/armstrong-numbers/rebar.lock
  exercises/practice/armstrong-numbers/src/armstrong-numbers.app.src
  exercises/practice/armstrong-numbers/src/armstrong-numbers.lfe
  exercises/practice/armstrong-numbers/test/armstrong-numbers-tests.lfe
Labels: x:module/practice-exercise, x:rep/large
