Repository exercism/lfe, pull requests merged in 2024-07, with the labels that each got.

#259 Add kindergarten-garden
  config.json
  exercises/practice/kindergarten-garden/.docs/instructions.md
  exercises/practice/kindergarten-garden/.docs/introduction.md
  exercises/practice/kindergarten-garden/.meta/config.json
  exercises/practice/kindergarten-garden/.meta/example.lfe
  exercises/practice/kindergarten-garden/.meta/tests.toml
  exercises/practice/kindergarten-garden/Makefile
  exercises/practice/kindergarten-garden/rebar.config
  exercises/practice/kindergarten-garden/rebar.lock
  exercises/practice/kindergarten-garden/src/kindergarten-garden.app.src
  exercises/practice/kindergarten-garden/src/kindergarten-garden.lfe
  exercises/practice/kindergarten-garden/test/kindergarten-garden-tests.lfe
Labels: x:module/practice-exercise, x:rep/large

#261 add pascals-triangle
  config.json
  exercises/practice/pascals-triangle/.docs/instructions.md
  exercises/practice/pascals-triangle/.docs/introduction.md
  exercises/practice/pascals-triangle/.meta/config.json
  exercises/practice/pascals-triangle/.meta/example.lfe
  exercises/practice/pascals-triangle/.meta/tests.toml
  exercises/practice/pascals-triangle/Makefile
  exercises/practice/pascals-triangle/rebar.config
  exercises/practice/pascals-triangle/rebar.lock
  exercises/practice/pascals-triangle/src/pascals-triangle.app.src
  exercises/practice/pascals-triangle/src/pascals-triangle.lfe
  exercises/practice/pascals-triangle/test/pascals-triangle-tests.lfe
Labels: x:module/practice-exercise, x:rep/large

#263 resistor-color-duo: sync
  exercises/practice/resistor-color-duo/.docs/instructions.md
Labels: x:size/tiny

#262 resistor-color: sync
  exercises/practice/resistor-color/.docs/instructions.md
Labels: x:size/tiny

#265 Expand language name
  config.json
Labels: x:rep/tiny

#264 Add knapsack exercise
  config.json
  exercises/practice/knapsack/.docs/instructions.append.md
  exercises/practice/knapsack/.docs/instructions.md
  exercises/practice/knapsack/.docs/introduction.md
  exercises/practice/knapsack/.meta/config.json
  exercises/practice/knapsack/.meta/example.lfe
  exercises/practice/knapsack/.meta/tests.toml
  exercises/practice/knapsack/Makefile
  exercises/practice/knapsack/include/item.lfe
  exercises/practice/knapsack/rebar.config
  exercises/practice/knapsack/rebar.lock
  exercises/practice/knapsack/src/knapsack.app.src
  exercises/practice/knapsack/src/knapsack.lfe
  exercises/practice/knapsack/test/knapsack-tests.lfe
Labels: x:module/practice-exercise, x:rep/large

#266 Fix: trailing white space and missing EOL
  exercises/practice/knapsack/.docs/instructions.append.md
  exercises/practice/knapsack/.meta/example.lfe
  exercises/practice/knapsack/include/item.lfe
  exercises/practice/knapsack/test/knapsack-tests.lfe
Labels: x:size/tiny, x:rep/tiny

#267 Bump rebar3_lfe version for resistor-color-duo
  exercises/practice/resistor-color-duo/rebar.config
Labels: x:rep/tiny
